language: php

php:
 - 5.3

before_install: composer self-update

install: composer install --dev

script:
 - phpunit --configuration tests/phpunit.xml
 - phpunit --configuration tests/phpunit-loader.xml