language: php

php:
 - 5.3
 - 5.5
 - 5.6
 - hhvm

before_install: composer self-update

install: composer install

script:
 - phpunit --configuration tests/phpunit.xml
 - phpunit --configuration tests/phpunit-loader.xml